#### Import des données pour les continents

In [1]:
#On utilise un echantilloneur de Gibbs avec balayage aléatoire
import pandas as pd 
import numpy as np

T=pd.read_csv("/Users/y.boukhateb/Desktop/Statapp Optimal Transport/Stat-App/DATA/dataset1.csv")
T.drop(T.columns[0], axis=1, inplace=True)
N=len(T.columns)-1
T.head()

/Users/y.boukhateb/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


/  North America  Central America  South America  \
0       North America          96102           208668          68240   
1     Central America        3233173           215008          36975   
2       South America         394674            26456         600759   
3        North Africa          62193               93            692   
4  Sub-Saharan Africa         478694              793          10738   

   North Africa  Sub-Saharan Africa  Northern Europe  Western Europe  \
0          4253               58827           248379          279267   
1           390                2414            42572           81356   
2           417               19431            68645          157063   
3         57855               12512            22807          404765   
4         44230             3717881           483736          430954   

   Southern Europe  Eastern Europe  Central Asia  Western Asia  South Asia  \
0           551959          162959         85259        131288         158   
1           190931            4962          3145          6236          14   
2          1200694           18644          5090         32516         351   
3           442162            5437          1382        367718           1   
4           312329            6442          2724        305291         243   

   East Asia  South-East Asia  Oceania  
0      39145            41758    52303  
1       1754              510     7541  
2     110426             2035    28490  
3        312              340     6858  
4       2918              576   149130

In [2]:
T_matrix = T.iloc[:, 1:].values

In [3]:
def histogramme(x):
    # Normaliser la liste pour que la somme soit égale à 1
    somme = np.sum(x)
    histogramme = x / somme
    return histogramme

### Création du code 

In [24]:
import ot
sigma=0.04

def proba_rejet(u,v,W,x,y,Z,T):
    u,v,W=histogramme(u),histogramme(v),histogramme(W)
    x,y,Z=histogramme(x),histogramme(y),histogramme(Z)
    return 1/(2*sigma**2)*(np.linalg.norm(T-ot.emd(u,v,W))**2-np.linalg.norm(T-ot.emd(x,y,Z))**2)

def in_hypercube(u,v,W):
    
    if any(x < 0 or x > 1 for x in u):
        return False
    
    if any(x < 0 or x > 1 for x in v):
        return False
    
    if any(any(x < 0 or x > 1 for x in row) for row in W):
        return False
    return True



SyntaxError: invalid syntax (2979209168.py, line 21)

In [25]:
# Graine aléatoire
np.random.seed(123)

# Taille de l'échantillon
n = 10**5
def MH_gibbs(T):
    N=len(T)
    # Initialisation
    U, V, C = np.zeros((n, N)), np.zeros((n, N)), np.zeros((n, N, N))
    U[0] = np.random.uniform(size=N)
    V[0] = np.random.uniform(size=N)
    C[0, :, :] = np.random.uniform(size=(N, N))
    def fix_coord(x):
        for i in range(N):
            x[i,i]=10
        return x
    # Vecteurs aléatoires
    e_u = np.random.normal(0, 0.02, (N, n))
    e_v = np.random.normal(0, 0.02, (N, n))
    e_C = np.random.normal(0, 0.04, (N, N, n))
    u_u = np.log(np.random.uniform(size=n))
    u_v = np.log(np.random.uniform(size=n))
    u_c = np.log(np.random.uniform(size=n))

    for k in range(n-1):
        # Pas pour U
        x, y, Z = U[k] + e_u[:, k], V[k], C[k]
        if not in_hypercube(x, y, Z):
            U[k+1], V[k+1], C[k+1] = U[k], V[k], C[k]
        else:
            if u_u[k] < proba_rejet(U[k], V[k], C[k], x, y, Z,T):
                U[k+1], V[k+1], C[k+1] = x, y, Z
            else:
                U[k+1], V[k+1], C[k+1] = U[k], V[k], C[k]
        UK=U[k+1]
        # Pas pour V
        x, y, Z = UK, V[k] + e_v[:, k], C[k]
        if not in_hypercube(x, y, Z):
            U[k+1], V[k+1], C[k+1] = UK, V[k], C[k]
        else:
            if u_v[k] < proba_rejet(UK, V[k], C[k], x, y, Z,T):
                U[k+1], V[k+1], C[k+1] = x, y, Z
            else:
                U[k+1], V[k+1], C[k+1] = UK, V[k], C[k]
        VK=V[k+1]
        # Pas pour C
        x, y, Z = UK, VK, fix_coord(C[k] + e_C[:, :, k])
        if not in_hypercube(x, y, Z):
            U[k+1], V[k+1], C[k+1] = UK, VK, C[k]
        else:
            if u_c[k] < proba_rejet(U[k], V[k], C[k], x, y, Z,T):
                U[k+1], V[k+1], C[k+1] = x, y, Z
            else:
                U[k+1], V[k+1], C[k+1] = UK, VK, C[k]
    return U,V,C

### Données simulées

In [26]:
u=np.array([0.1,0.4,0.5])
v=np.array([0.6,0.35,0.05])
C=[[10,3,5],[6,10,2],[8,8,10]]
T=ot.emd(u,v,C)
U,V,W=MH_gibbs(T)

In [19]:
a=np.array([0.2,0,0.8])
b=np.array([0.3,0.5,0.2])
D=[[10,3,5],[6,10,3],[1,0,10]]
T=ot.emd(a,b,D)
P,O,I=MH_gibbs(T)

### Comparaison et affichage des résultats

In [27]:
M=np.mean(W,axis=0)
print(histogramme(M),
histogramme(C),
ot.emd2(u,v,histogramme(C)),
ot.emd2(u,v,histogramme(M)))

[[0.21760111 0.15194244 0.10670385]
 [0.0869987  0.07614054 0.16175348]
 [0.09730556 0.01324067 0.08831365]] [[0.16129032 0.0483871  0.08064516]
 [0.09677419 0.16129032 0.03225806]
 [0.12903226 0.12903226 0.16129032]] 0.10483870967741934 0.07024479452017159


In [20]:
N=np.mean(I,axis=0)
print(histogramme(N),
histogramme(C),
ot.emd2(u,v,histogramme(D)),
ot.emd2(u,v,histogramme(N)))

[[0.12844191 0.13253317 0.06903084]
 [0.11018558 0.11920986 0.11693357]
 [0.08636198 0.0882168  0.14908629]] [[0.16129032 0.0483871  0.08064516]
 [0.09677419 0.16129032 0.03225806]
 [0.12903226 0.12903226 0.16129032]] 0.06 0.09777804671332793


In [23]:
print(W[:2,:,:],np.mean(W[:2,:,:],axis=0))

[[[0.9807642  0.68482974 0.4809319 ]
  [0.39211752 0.34317802 0.72904971]
  [0.43857224 0.0596779  0.39804426]]

 [[0.94265846 0.75103985 0.48012374]
  [0.4317363  0.27122706 0.72738501]
  [0.4603055  0.02925963 0.47029492]]] [[0.96171133 0.71793479 0.48052782]
 [0.41192691 0.30720254 0.72821736]
 [0.44943887 0.04446876 0.43416959]]
